### ISSUE TITLE
'dimension' missing in the model_audit.sql file

### ISSUE THREAD

**Issue by katiejohnsonsf** [kristeligt-dagblad/dbt_ml#41]
In running dbt to get feature information for a linear regression model, I encountered this error: 

```
Database Error in model linear_reg (models/linear_reg.sql)
19:58:19    Query column 5 has type ARRAY<STRUCT<input STRING, min FLOAT64, max FLOAT64, ...>> which cannot be inserted into column feature_info, which has type ARRAY<STRUCT<input STRING, min FLOAT64, max FLOAT64, ...>
```
We discovered that bigquery_ml was attempting to write a column named dimension which was not present in the schema to the feature info array. To fix, we added `dimension int64` to line 8 in the model_audit.sql file which ran without the error.

**Comment by rbjerrum** [comment]
This is corrected in latest version.
