### ISSUE TITLE
Unrecognized name: loss for ARIMA_PLUS (not ARIMA)

### ISSUE THREAD

**Issue by pnd-jarnold** [kristeligt-dagblad/dbt_ml#56]
Hey all, I am struggling with a bug, where I get the error message 

10:40:48    Database Error in model ml_sku_forecast (models/ml/ml_sku_forecast.sql)
  Unrecognized name: loss at [14:63]

when using ARIMA_PLUS, when using ARIMA this does not happen. I am assuming it is due the post hook but I cannot pin it down.

using version 0.6.0 of the package, dbt-bigquery==1.8.1, dbt-core==1.8.2

**Comment by RyanBalshaw** [comment]
Hi @lewisd-benefex, 

Apologies for commenting on a closed issue but I believe it is relevant to my issue.

I am on version 0.6.1 of `dbt_ml`:
![image](https://github.com/user-attachments/assets/fcd4ff42-a1a8-4cff-9913-b44605e15f96)

and I am using `dbt-bigquery=1.8.2` and  `dbt-core==1.8.3`:
![image](https://github.com/user-attachments/assets/d0d2491c-5be7-42bf-9ea3-08fd3d823518)

I still find that this error occurs when using the ARIMA_PLUS model. I checked the update hook and verified that the variables are defined as you described above (e.g., `cast(null as float64) as loss`). However, I encounter:

`Database Error in model custom_arima_model (local/path/to/custom_arima_model.sql) Unrecognized name: loss at [14:63]`

My materialization configuration is as follows:
```
{% set arima_historical_window_length = var("arima_historical_window_length") | int %}
{% set arima_forecast_window_length = var("arima_forecast_window_length") | int %}
{% set max_arima_order = 4 %}

{{
    config(
        materialized="model",
        ml_config={
            "MODEL_TYPE": "ARIMA_PLUS",
            "TIME_SERIES_DATA_COL": "run_hours",
            "TIME_SERIES_TIMESTAMP_COL": "final_time",
            "TIME_SERIES_ID_COL": "entity_id",
            "AUTO_ARIMA": true,
            "HORIZON": arima_forecast_window_length,
            "DATA_FREQUENCY": "DAILY",
            "AUTO_ARIMA_MAX_ORDER": max_arima_order,
            "DECOMPOSE_TIME_SERIES": true,
        },
    )
}}
```
Notably, I verified that the model information is written to the `project_id.audit.ml_models` table, there just seems to be some issue restricting the `dbt run` from passing. I believe the main issue is in the compiled BigQuery query:
![image](https://github.com/user-attachments/assets/9351d740-a045-4566-a7e9-9a45b2bb2225)



Any advice would be greatly appreciated! Thanks in advance.

**Comment by lewisd-benefex** [comment]
I’d say raise it as a new issue and refer back to this issue by all means as I’m unsure the impact on custom models I was testing my changes using standard model config

**Comment by RyanBalshaw** [comment]
Will do, thanks for the advice!

**Comment by lewisd-benefex** [comment]
It's basic I believe:

`{{
    config(
        materialized='model',
        ml_config={
            'model_type': 'ARIMA',
            'TIME_SERIES_DATA_COL': 'employee_monthly_cost_transformed_usd',
            'TIME_SERIES_TIMESTAMP_COL': 'month',
            'DATA_FREQUENCY': 'MONTHLY',
            'TIME_SERIES_ID_COL': ['customer_id', 'country', 'currency', 'benefit_type', 'provider']
        }
    )
}}`

**Comment by RyanBalshaw** [comment]
Thanks! I will test out this config and see if this makes a difference. I appreciate the prompt response.

I will try and see if I can resolve the issue locally. I am hoping it may be as simple as just updating some of the logic in the `bigquery__create_model_as` macro or downstream in the `model_options` macro. I think this is a good place to start because the issue I have stems from the compiled sql that is passed to BigQuery.

**Comment by RyanBalshaw** [comment]
Solve the issue, it is pretty trivial but hard to diagnose as well as it only breaks in the `model_audit` macro: 
> {{
>     config(
>         materialized="model",
>         ml_config={
>             "MODEL_TYPE": "ARIMA_PLUS",
>             "TIME_SERIES_DATA_COL": "run_hours",
>             "TIME_SERIES_TIMESTAMP_COL": "final_time",
>             "TIME_SERIES_ID_COL": "entity_id",
>             "AUTO_ARIMA": true,
>             "HORIZON": arima_forecast_window_length,
>             "DATA_FREQUENCY": "DAILY",
>             "AUTO_ARIMA_MAX_ORDER": max_arima_order,
>             "DECOMPOSE_TIME_SERIES": true,
>         },
>     )
> }}


`MODEL_TYPE` is required to be lowercase, i.e., it must be `model_type`. I assumed that case insensitivity was the default as this is how it appears to be in the BigQuery [create model statement](https://cloud.google.com/bigquery/docs/reference/standard-sql/bigqueryml-syntax-create) but I didn't consider how the config is accessed by the underlying `dbt_ml` macros. `dbt_ml` makes use of the [dbt config variable](https://docs.getdbt.com/reference/dbt-jinja-functions/config) to access the config as a dictionary and when accessing these dictionary keys the process is case sensitive.

Thanks for the help @lewisd-benefex.
